"""Employee domain validators re-exported from the legacy validation layer."""

from app.core.validation import (
    calcular_digito_verificador_clabe,
    cuenta_parece_clabe,
    normalizar_clabe_interbancaria,
    normalizar_cuenta_bancaria,
    normalizar_nombre_banco,
    validar_apellido_materno_empleado,
    validar_apellido_paterno_empleado,
    validar_banco_empleado,
    validar_clabe_empleado,
    validar_contacto_emergencia_nombre,
    validar_contacto_emergencia_telefono,
    validar_cuenta_bancaria_empleado,
    validar_curp_empleado,
    validar_email_empleado,
    validar_fecha_nacimiento_empleado,
    validar_genero_empleado_requerido,
    validar_nombre_empleado,
    validar_nss_empleado,
    validar_nss_empleado_requerido,
    validar_rfc_empleado,
    validar_rfc_empleado_requerido,
    validar_telefono_empleado,
    validar_telefono_empleado_requerido,
    verificar_clabe,
)

validators___all__ = [
    "calcular_digito_verificador_clabe",
    "cuenta_parece_clabe",
    "normalizar_clabe_interbancaria",
    "normalizar_cuenta_bancaria",
    "normalizar_nombre_banco",
    "validar_apellido_materno_empleado",
    "validar_apellido_paterno_empleado",
    "validar_banco_empleado",
    "validar_clabe_empleado",
    "validar_contacto_emergencia_nombre",
    "validar_contacto_emergencia_telefono",
    "validar_cuenta_bancaria_empleado",
    "validar_curp_empleado",
    "validar_email_empleado",
    "validar_fecha_nacimiento_empleado",
    "validar_genero_empleado_requerido",
    "validar_nombre_empleado",
    "validar_nss_empleado",
    "validar_nss_empleado_requerido",
    "validar_rfc_empleado",
    "validar_rfc_empleado_requerido",
    "validar_telefono_empleado",
    "validar_telefono_empleado_requerido",
    "verificar_clabe",
]

__all__ = validators___all__
