"""
Constantes compartidas del dominio.
"""
from .permisos import (
    PERMISOS_DEFAULT,
    MODULOS_CON_AUTORIZACION,
    MODULOS_PERMISOS,
    OPCIONES_ROLES_EMPRESA,
    ROLES_ASIGNABLES_POR_ADMIN_EMPRESA,
)

__all__ = [
    "PERMISOS_DEFAULT",
    "MODULOS_CON_AUTORIZACION",
    "MODULOS_PERMISOS",
    "OPCIONES_ROLES_EMPRESA",
    "ROLES_ASIGNABLES_POR_ADMIN_EMPRESA",
]
